config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # Custom Lists
  resources :custom_lists
  get '/customrandomfilm' => 'custom_lists#rand'

  # Films
  resources :films, except: :create
  post "/films" => "films#multiple_film_results", :as => 'filmsubmission'
  post "/films/new" => "films#create", :as => 'new_film_path'
  get 'films/confirmation'
  get '/randomfilm' => 'films#randomconfirm'
  get '/random_film_confirmation' => 'films#randomconfirm'
  post '/random_film_confirmation' => 'films#wheel'

  # Pages
  get '/api' => 'pages#api'
  get 'pages/login'
  get 'pages/logout'
  post 'pages/login'
  post 'pages/logout'
  delete 'pages/logout' => 'pages#destroy'

  # Genres
  resources :genres

  # People
  post 'people_path' => 'people#add_film_to_person', as: 'add_film_to_person'
  get 'people/watched_films' => 'people#watched_films'
  get 'people/unwatched_films' => 'people#render_unwatched_films'
  resources :people

  # Watched
  post '/people/:id' => 'watches#create'
  post '/films/:id' => 'watches#create'
  resources :watches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :films, dependent: :nullify
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to(@genre, notice: "Genre was successfully created.") }
        format.json { render(:show, status: :created, location: @genre) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @genre.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to(@genre, notice: "Genre was successfully updated.") }
        format.json { render(:show, status: :ok, location: @genre) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @genre.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to(genres_url, notice: "Genre was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td><%= link_to 'Show', genre %></td>
        <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
        <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<br>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>

<p>
Films:
</p>

<ul>
  <% @genre.films.each do |film| %>
  <li><%= link_to film.title, film_path(film) %></li>
  <% end %>
</ul>

<p>
<%= link_to 'Add new film', new_film_path %>
</p>