config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # Custom Lists
  resources :custom_lists
  get '/customrandomfilm' => 'custom_lists#rand'

  # Films
  resources :films, except: :create
  post "/films" => "films#multiple_film_results", :as => 'filmsubmission'
  post "/films/new" => "films#create", :as => 'new_film_path'
  get 'films/confirmation'
  get '/randomfilm' => 'films#randomconfirm'
  get '/random_film_confirmation' => 'films#randomconfirm'
  post '/random_film_confirmation' => 'films#wheel'

  # Pages
  get '/api' => 'pages#api'
  get 'pages/login'
  get 'pages/logout'
  post 'pages/login'
  post 'pages/logout'
  delete 'pages/logout' => 'pages#destroy'

  # Genres
  resources :genres

  # People
  post 'people_path' => 'people#add_film_to_person', as: 'add_film_to_person'
  get 'people/watched_films' => 'people#watched_films'
  get 'people/unwatched_films' => 'people#render_unwatched_films'
  resources :people

  # Watched
  post '/people/:id' => 'watches#create'
  post '/films/:id' => 'watches#create'
  resources :watches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :films
  has_many :custom_lists
  has_many :film_ids

  has_secure_password
  validates :password, length: { in: 8..20 }, presence: true, on: :create
  validates :username, :email, uniqueness: true

  def get_person_films_list
    myfilmslist = Film.where(id: film_id)
    myfilms = myfilmslist.map(&:title)

    myfilms.each do |film|
      object = Film.where(title: [film.to_s])
      id = object.pluck(:id)
      title = object.pluck(:title)
      title = title.join
    end
  end

  def get_watched_films
    my_watches = Watch.where(person_id: id)
    film_list = []
    my_watches.each do |w|
      film_list << Film.find(w.film_id)
    end
    film_list
  end

  def get_unwatched_films
    watched_film_ids = Watch.where(person_id: id).pluck(:film_id)
    Film.where.not(id: watched_film_ids)
  end

  def self.search_unwatched_films(person, search)
    if search
       unwatched_films = person.get_unwatched_films
       unwatched_films.select { |film| film.title.downcase.include?(search.downcase.rstrip) }
    else
      @unwatched_films = Person.get_unwatched_films
    end
  end

  def remove_film_id_from_person(id)
    id = id.to_s
    if film_id.include?(id)
      film_id.delete(id)
      save
      "film id deleted"
    else
      "id not found"
    end
  end

  def add_film_id_to_person(person, id)
    if person.film_id.exclude?(id)
      person.film_id << id
      person.save!
    else
      flash.alert = 'Film not saved'
    end
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  include Pagy::Backend

  before_action :set_person, only: %i[show edit update destroy watched_films render_unwatched_films]
  before_action :authorized, only: %i[show edit update destroy]
  before_action :authorize!, only: %i[show update edit destroy]
  # skip_before_action :authorized, only: [:new]

  def watched_films
    @linked_films = @person.get_watched_films
    respond_to do |format|
      format.html { render(:watched_films) }
    end
  end

  def render_unwatched_films
    @attributes = PersonPresenter.new(@person, search_params: params[:search]).attributes
    @pagy, @films = pagy_array(@attributes[:unwatched_films])
    respond_to do |format|
      format.html { render(:show) }
    end
  end

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
    @person.id
    @attributes = PersonPresenter.new(@person).attributes

    @pagy, @films = pagy(@attributes[:unwatched_films], items: 32)
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)
    respond_to do |format|
      if @person.save
        format.html { redirect_to(@person, notice: 'Person was successfully created.') }
        flash.alert = 'Person updated'
        format.json { render(:show, status: :created, location: @person) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @person.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to(@person, notice: 'Person was successfully updated.') }
        format.json { render(:show, status: :ok, location: @person) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @person.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to(people_url, notice: 'Person was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  def authorize!
    @person = Person.find(params[:id])
    return unless @person != current_user

    flash[:error] = "You don't have access to this section."
    redirect_to('/')
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:username, :password, :salt, :encrypted_password, :email, :film_id, :search)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  include Pagy::Frontend
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
      <%= form.label :password %>
      <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.username %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%# if !flash.empty? and !flash.alert.empty?  %>
  <%# flash.alert.each do |error| %>
  <div class="alert error"> <%#= error %></div>
  <% if @person.errors.any? %>
      <% @person.errors.each do |error| %>
        <%= error.full_message %>
        <p></p>
        <% end %>
  <% end %>
<%# end %>
<%# end %>
<%= form_for(@person) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: :username  %>
  <p></p>
  <%= f.label :email %>
  <%= f.text_field :email, placeholder: :email  %>
  <p></p>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: :password %>
  <p></p>
  <%= submit_tag "Create" %>
<% end %>
<p></p>
<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<%= javascript_pack_tag 'person.js' %>

<p id="notice"><%= notice %></p>

<%= form_tag people_unwatched_films_path(id: @person.id), method: :get do %>
  <%= hidden_field_tag :id, @person.id %>
  <%= text_field_tag :search, params[:search], placeholder: "Search..." %>
  <%= submit_tag("Search", name: nil) %>
<% end %>

<br>

<%= link_to "View watched films", people_watched_films_path(:id => @person.id), {:style=>'font-size:22px;',} %>

<div class="films-watched">
  <h3 class="films-watched-title">Films watched in <%= Time.current.year %> </h3>
  <h2 class = "films-watched-count"><%= @attributes[:watch_count] %></h2>
</div>

<br><br><br>
<h2>My films to watch</h2>

<div class="container">
<% @films.each do |film| %>
    <div class="col-md-4 unwatched-films-row">
      <%= link_to film do %>
        <div class="img-container">
          <%= image_tag('https://image.tmdb.org/t/p/w780' << film.poster_path.to_s, class: "film") %>
        </div>
      <% end %>
      <p class="title"><%= film.title %></p> 
      <%= form_for :watch do |f| %>
        <%= f.hidden_field :person_id, value: @person.id %>
        <%= f.hidden_field :film_id, value: film.id %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= f.submit %>
      <% end %>
  </div>
<% end %>
</div>


<%== pagy_nav(@pagy) %>

app/views/people/unwatched_films.html.erb
<h1>My unwatched films</h1>

<% @unwatched_films.each do |f|  %>
    <%= link_to f.title, film_path(f.id)%>
    <br>
<% end %>

app/views/people/watched_films.html.erb
<h1>My watched films</h1>

<% @linked_films.each do |f|  %>
    <%= link_to f.title, film_path(f.id)%>
    <br>
<% end %>