config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # Custom Lists
  resources :custom_lists
  get '/customrandomfilm' => 'custom_lists#rand'

  # Films
  resources :films, except: :create
  post "/films" => "films#multiple_film_results", :as => 'filmsubmission'
  post "/films/new" => "films#create", :as => 'new_film_path'
  get 'films/confirmation'
  get '/randomfilm' => 'films#randomconfirm'
  get '/random_film_confirmation' => 'films#randomconfirm'
  post '/random_film_confirmation' => 'films#wheel'

  # Pages
  get '/api' => 'pages#api'
  get 'pages/login'
  get 'pages/logout'
  post 'pages/login'
  post 'pages/logout'
  delete 'pages/logout' => 'pages#destroy'

  # Genres
  resources :genres

  # People
  post 'people_path' => 'people#add_film_to_person', as: 'add_film_to_person'
  get 'people/watched_films' => 'people#watched_films'
  get 'people/unwatched_films' => 'people#render_unwatched_films'
  resources :people

  # Watched
  post '/people/:id' => 'watches#create'
  post '/films/:id' => 'watches#create'
  resources :watches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/api.erb
<% require 'json' %>

<h1>Hello API</h1>

<% response = @response.parsed_response %>

<% results = response["results"] %>

<% film = results[0].to_h  %>
<pre>
<%= JSON.pretty_generate(film) %>

</pre>
<%= film["id"] %> <br />
<%= film["title"] %>

app/views/pages/home.html.erb

<%= javascript_pack_tag 'home.js' %>


<h2>Movie Picker</h2>


<div class="home-container">

    <%= link_to new_film_path, class: "home-button" do %>

    <div class="home-button-text">
      <h3>Add New Movie</h3>
      <p>Add a new film to list</p>
    </div>
    <% end %>

  <% if logged_in? %>
  <%= link_to person_path(current_user.id), class: "home-button" do %>
    <div class="home-button-text">
      <h3>Show Movies</h3>
      <p>Show all my films</p>
    </div>
    <% end %>
  <% end %>

    <%= link_to randomfilm_path, class: "home-button" do %>
    <div class="home-button-text">
      <h3>Random Movie</h3>
      <p>Select a random film from all films</p>
    </div>
    <% end %>


    <%= link_to new_custom_list_path, class: "home-button" do %>
    <div class="home-button-text">
      <h3>Create Custom List</h3>
      <p>Create a curated list of films</p>
    </div>
    <% end %>
</div>
<br/><br/>

<% if logged_in? %>

  <% watches = Watch.where(person_id: current_user.id, created_at: Time.current.all_year)  %>
  <div class="home-films-watched">
  <h3 class="home-films-watched-title">Films watched in <%= Time.current.year %> </h3>
  <h2 class = "home-films-watched-count"><%= watches.count %></h2>
  </div>

<% end %>

<br/><br/>
<section class="questions">
  <div class="title">
    <h2>FAQ</h2>
  </div>
  <div class="section-center">
    <article class="question" data-controller="faq" data-faq-change-class="show-text">
      <div class="question-title">
        <p>How does Movie Picker work?</p>
        <button data-action="click->faq#show" type="button" class="question-btn">
          <span class="faq-arrow">▼</span>
        </button>
      </div>
<div class="question-text">
  <p>Movie Picker allows you to create a personalised list of movies, select one at random and see detailed information about the movie.</p>
</div>
    </article>
    <article class="question" data-controller="faq" data-faq-change-class="show-text">
      <div class="question-title">
        <p>How do I add movies to my list?</p>
        <button data-action="click->faq#show" type="button" class="question-btn">
          <span class="faq-arrow">▼</span>
        </button>
      </div>
<div class="question-text">
  <p>First, log in (or register if you haven't created an account). Select 'Add new movie' to add a film to your personal list. You can view all of your current films by selecting 'Show Movies'.</p>
</div>
    </article>
  </div>
</section>
<br/>
<br/>
<% if logged_in? %>
  <div class="banner" id="banner">
  <% controller = FilmsController.new %>
  <% films = controller.unwatched_films %>
  <% films.each do |f| %>
    <%= link_to image_tag('https://image.tmdb.org/t/p/w154' << f['poster_path'].to_s), f, class: "film" %>
  <% end %>
  </div>
<% end %>

app/views/pages/login.erb
<h1>Login</h1>
<form action="/pages/login" method="POST">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="username" placeholder="username"/>
  <input type="password" name="password" placeholder="password"/>
  <button type="submit" class="login-form-button">Submit</button>
</form>

app/views/pages/logout.html.erb
<h1>Logout Page</h1>

<%= link_to "Logout", pages_logout_path, method: :delete %>
<br>