config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  # Custom Lists
  resources :custom_lists
  get '/customrandomfilm' => 'custom_lists#rand'

  # Films
  resources :films, except: :create
  post "/films" => "films#multiple_film_results", :as => 'filmsubmission'
  post "/films/new" => "films#create", :as => 'new_film_path'
  get 'films/confirmation'
  get '/randomfilm' => 'films#randomconfirm'
  get '/random_film_confirmation' => 'films#randomconfirm'
  post '/random_film_confirmation' => 'films#wheel'

  # Pages
  get '/api' => 'pages#api'
  get 'pages/login'
  get 'pages/logout'
  post 'pages/login'
  post 'pages/logout'
  delete 'pages/logout' => 'pages#destroy'

  # Genres
  resources :genres

  # People
  post 'people_path' => 'people#add_film_to_person', as: 'add_film_to_person'
  get 'people/watched_films' => 'people#watched_films'
  get 'people/unwatched_films' => 'people#render_unwatched_films'
  resources :people

  # Watched
  post '/people/:id' => 'watches#create'
  post '/films/:id' => 'watches#create'
  resources :watches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<header class="nav">
  <div>
    <nav class="nav">
      <ul class="nav_bar <%= logged_in? ? 'nav-logged-in' : 'nav-logged-out' %>">
        <li class="nav_list"><%= link_to "Home", root_path %></li>

        <% if logged_in? %>
          <li class="nav_list"><%= link_to "Random Film", randomfilm_path %></li>
          <li class="nav_list"><%= link_to "Profile", person_path(current_user.id) %></li>

          <li class="sign_in_status <%= logged_in? ? 'sign-in-status-right-align' : 'sign-in-status-center-align' %>">
            <p class="username"><%= current_user.username %></p>
            <%= button_to "Logout", pages_logout_path, method: :get, form_class: "login-button" %>
          </li>

        <% else %>
          <li class="sign_in_status">
            <%= button_to "Login", pages_login_path, method: :get %>
            <%= button_to "Register", new_person_path, method: :get %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviePicker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render "layouts/navbar" %>
  <% flash.each do |type, msg| %>
    <div>
      <h3><%= msg %></h3>
    </div>
  <% end %>
  
  </body>
  <%= yield %>


</html>